### ISSUE TITLE
Additional info is not shown: Most wanted Track numbers and track duration 

### ISSUE THREAD

**Issue by Martin-Zentner** [torum/MPDCtrl#16]
I'am running MPDCtrl v3.0.21.0 on Windows 11. With a large MP3/FLAC library on my NAS.
A Rasperry Pi 4 is running Hifberry (including an MPD daemon) with a good hardware DAC HAT.

=> Playback is nice, but there are some issues with MPDCtrl:

1) Library only shows Filename and path per title, additional information cannot be shown.

2) Queue shows a position per track but that's just for ordering the playing sequence. '
The position actually changes when you move a single entry up or down.

3) Search shows at least some information including a time coulmn, but this is giving wrong time values.
While Genre and Last Modified are shown track/disc number and correct duration per track are missing.

**Comment by torum** [comment]
Thank you very much for your feedback and very sorry for the very long delay in response... 

1. For the "Library", the MPD's "listall" command only returns directories and the file name and its path like below. 
```
>listall
<directory: ZZ Top/Unknown Album
<file: ZZ Top/Unknown Album/La Grange.mp3
```
That's why MPDCtrl only shows file name and path. However, as of now, there maybe a better ways to get all the files in the MPD database in one go. I will definitely look into it. Thank you.

2. "position" in the queue list is, as you know, "ordering the playing sequence". You are right and it's not a Track number.

3. About search result giving "wrong time values" is strange. I just checked a few trucks for myself, but they seem to be correct durations. 

So, for now, what I can do is, to add truck number in the queue list (should be straight forward) and find a way to get them and show in search result and playlist view as well.
