### ISSUE TITLE
Incomplete rendering of tracks in the queue and playlist tabs with seemingly random frequency

### ISSUE THREAD

**Issue by Neo-Desktop** [torum/MPDCtrl#4]
Hello!
I would like to thank you so much for creating such a wonderful, open-source, application.

I seem to be having an issue with seeing tracks added to playlists or queues after specific files.
The queue will appear fully blank even if there are many tracks enqueued. The same applies to playlists.

What I'm currently seeing:
![image](https://user-images.githubusercontent.com/321592/120382354-651c2580-c2d8-11eb-9abd-5331f4ac428a.png)

There are 8 tracks visible in this playlist, but MPD reports 261 total tracks in the same playlist.

The same issues are visible in the Queue
![image](https://user-images.githubusercontent.com/321592/120382571-a7ddfd80-c2d8-11eb-9f46-540c9bc7fa5c.png)

The Library does not appear to be affected by this bug
![image](https://user-images.githubusercontent.com/321592/120382683-c9d78000-c2d8-11eb-930a-c16cc829d9ba.png)

I would be expecting the interface to present all the tracks enqueued or added to the playlists as seen here
![image](https://user-images.githubusercontent.com/321592/120382826-fbe8e200-c2d8-11eb-83da-18a37529d54b.png)

If I have a spare moment I'll take a look at the source code to identify the possible problem and suggest a potential fix.
Thank you again!

**Comment by torum** [comment]
Thank you so much for the detailed report! This sounds like the same bug reported in the "Discussions" page about a month ago.
#3 

Unfortunately, I have not found the cause of the bug yet. The problem is that I can't reproduce the bug in my environment. I hate to ask you but, if it is OK, could you copy the queue in the debug log (bottom right window) and paste it here? (or you could mail it to me) 

It looks something like this below. I'd very much like to test and find the cause. Thank you in advance.

`>>>>playlistinfo`

`<<<<file: John Lee Hooker/The Very Best Of John Lee Hooker/One Bourbon, One Scotch, One Beer.mp3`
`<<<<Last-Modified: 2021-01-07T12:52:08Z`
`<<<<Artist: John Lee Hooker`
`<<<<Album: The Very Best Of John Lee Hooker`
`<<<<Title: One Bourbon, One Scotch, One Beer`
`<<<<Genre: Blues`
`<<<<Date: 2002`
`<<<<Time: 187`
`<<<<duration: 187.380`
`<<<<Pos: 324`
`<<<<Id: 653`
`<<<<file: John Lee Hooker/The Very Best Of John Lee Hooker/Shake It Baby.mp3`
`<<<<Last-Modified: 2021-01-07T12:49:40Z`
`<<<<Artist: John Lee Hooker`
`<<<<Album: The Very Best Of John Lee Hooker`
`<<<<Title: Shake It Baby`
`<<<<Genre: Blues`
`<<<<Date: 2002`
`<<<<Time: 251`
`<<<<duration: 250.976`
`<<<<Pos: 325`
`<<<<Id: 654`
`<<<<file: John Lee Hooker/The Very Best Of John Lee Hooker/Terraplane Blues with Roy Rogers.mp3`
`<<<<Last-Modified: 2021-01-07T12:53:20Z`
`<<<<Artist: John Lee Hooker`
`<<<<Album: The Very Best Of John Lee Hooker`
`<<<<Title: Terraplane Blues with Roy Rogers`
`<<<<Genre: Blues`
`<<<<Date: 2002`
`<<<<Time: 176`
`<<<<duration: 176.297`
`<<<<Pos: 326`
`<<<<Id: 655`
`<<<<file: John Lee Hooker/The Very Best Of John Lee Hooker/You Know, I Know.mp3`
`<<<<Last-Modified: 2021-01-07T12:51:38Z`
`<<<<Artist: John Lee Hooker`
`<<<<Album: The Very Best Of John Lee Hooker`
`<<<<Title: You Know, I Know`
`<<<<Genre: Blues`
`<<<<Date: 2002`
`<<<<Time: 245`
`<<<<duration: 245.350`
`<<<<Pos: 327`
`<<<<Id: 656`
`<<<<OK`

**Comment by torum** [comment]
I think I know the cause... My initial theory was wrong. It wasn't parsing. It's the updates. Your screenshot gives me an idea (Thanks). You turns "consume" mode on. It means the entire queue list updates every time song changes. And it may cause conflict in some situation especially if you have a long queue list. When you turns "consume" mode on and change songs rapidly, MPDCtrl receives flood of huge queue lists from MPD asynchronously.

**Comment by torum** [comment]
I just uploaded a new version (v3.0.6) to Microsoft Store. It should be available within a few days. It may or may not fix your problem. It might have been a different bug. Hope you try it out and see it's been fixed. Thank you in advance!

**Comment by Neo-Desktop** [comment]
Hello! Sorry about the delay, I saw your message last night and forgot to respond.

Thank you for looking into this! I can still provide the debug log if you'd like, I'll gather the information shortly

**Comment by Neo-Desktop** [comment]
Attached are the debug logs as requested -

I have noticed that only certain tracks (or rather tracks by a particular artist) seem to fault the application.

[2021-06-03-MPD_Ctrl_Debug.log](https://github.com/torum/MPDCtrl/files/6594059/2021-06-03-MPD_Ctrl_Debug.log)

For completeness, this is what is shown in the GUI.
![image](https://user-images.githubusercontent.com/321592/120704605-a2fd8300-c46b-11eb-8068-f9495e21fe03.png)

Thank you again!

**Comment by torum** [comment]
Thank you so much for the log!

> I have noticed that only certain tracks (or rather tracks by a particular artist) seem to fault the application.

Interesting... then it could be a different bug.

I'll debug the app using the logs you gave. Thank you very much.

**Comment by torum** [comment]
Ah-ha!

> 'System.ArgumentException' (System.Private.CoreLib.dll)
>Exception@ParsePlaylistInfo: An item with the same key has already been added. Key: Genre

<<<<file: Harris Heller/Synthwave/Sunset/01 - Zig the Zag.flac
<<<<Last-Modified: 2021-06-03T16:52:10Z
<<<<Album: Sunset
<<<<AlbumArtist: Harris Heller
<<<<Artist: Harris Heller
<<<<Date: 2021-03-05
<<<<Disc: 1
**<<<<Genre: Electro**
**<<<<Genre: Dance**
<<<<Title: Zig the Zag
<<<<Track: 1
<<<<Time: 126
<<<<duration: 126.250
<<<<Pos: 6
<<<<Id: 1439

I've never expected to receive duplicated "Genre"!

Finally! Thank you so much!

**Comment by Neo-Desktop** [comment]
Ah, wow! Very interesting, I actually had no idea one could add duplicate entries to the metadata tags
The tracks in question came to me pre-tagged in this case

I was intrigued and decided to take a look at how different media players and tag editors rendered the metadata for files with duplicate tag entries.

Mp3tag will render the multiple Genres as `Electro\\Dance` in the editor textbox, but in the "Extended Tag Editor" have multiple entries of the `GENERE` tag. Interestingly enough, the Mp3Tag file properties window for the track only shows `Electro` as the genre.
The Windows file properties dialog renders the genre field as `Electro; Dance`
VLC simply combines them with a space character making `Electro Dance`
MPC-HC's MediaInfo renders the tag as `Electro / Dance`

It appears there isn't one standardized solution for this, but it's quite fascinating, nonetheless!

Let me know if you need anything further from me :)

Thanks!

**Comment by torum** [comment]
I was gonna check the same thing! You beat me (and did whole lot better). :-) 
A quick search told me it isn't popular but there is no standard way.

I just uploaded a yet another new version (v3.0.7) to Microsoft Store. So, I'd much appreciate it if you could check to see if it works.
Thank you very much again!

**Comment by Neo-Desktop** [comment]
It appears to be working quite well now!

This is very exciting :)
![image](https://user-images.githubusercontent.com/321592/120799178-3fb73380-c4f3-11eb-98a5-90c20e57fd16.png)

Thank you for the prompt resolution, I really appreciate your hard work!
